apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata: 
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'deepakverma.dv0598@gmail.com'
    #privatekey is used for associating the secret that letsencrypt going to send for verification
    privateKeyRef:
      name: letsencrypt-prod
    # its only specifying that when letencrypt going to use a url for verification then just respond on that.
    solvers:
      - http01:
          ingress:
            class: nginx
